# Generated by Django 4.2.11 on 2024-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=50)),
                ('task_status', models.CharField(max_length=50)),
                ('task_start_time', models.DateTimeField()),
                ('task_end_time', models.DateTimeField()),
                ('task_result', models.CharField(max_length=50)),
                ('task_error', models.CharField(max_length=50)),
                ('task_progress', models.FloatField()),
                ('task_info', models.TextField()),
            ],
        ),
    ]
