# Generated by Django 4.2.11 on 2024-05-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_error',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_progress',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_result',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
        migrations.AddField(
            model_name='task',
            name='opt_type',
            field=models.CharField(default='hpo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start_time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
