# Generated by Django 4.2.11 on 2024-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_board', '0002_remove_task_task_error_remove_task_task_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50)),
                ('configuration', models.TextField()),
                ('performance', models.FloatField()),
                ('time_consumed', models.FloatField()),
            ],
        ),
    ]
