# Generated by Django 4.2.11 on 2024-05-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_board', '0003_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
