# Generated by Django 4.2.11 on 2024-05-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_board', '0004_observation_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='index',
            new_name='idx',
        ),
    ]
